<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class addSpanishPlants extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'addSpanishPlants';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Add the plant species that Natcho requested. Made on Feb. 6th 2023.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $plantSGid = \App\Models\Speciesgroup::where('name', 'plants')->first()->id;

        $rigens = \App\Models\Species::where('genus', 'Gazania')->where('taxon', 'rigens')->first(); if ($rigens == null) {$rigens = \App\Models\Species::create(['genus' => 'Gazania', 'taxon' => 'rigens', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $rigens->esname = 'Gazania'; $rigens->save();}
        $hybrida = \App\Models\Species::where('genus', 'Arctotis')->where('taxon', 'hybrida')->first(); if ($hybrida == null) {$hybrida = \App\Models\Species::create(['genus' => 'Arctotis', 'taxon' => 'hybrida', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $hybrida->esname = 'Margarita africana'; $hybrida->save();}
        $amelloides = \App\Models\Species::where('genus', 'Felicia')->where('taxon', 'amelloides')->first(); if ($amelloides == null) {$amelloides = \App\Models\Species::create(['genus' => 'Felicia', 'taxon' => 'amelloides', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $amelloides->esname = 'Margarita azul'; $amelloides->save();}
        $cordifolia = \App\Models\Species::where('genus', 'Aptenia')->where('taxon', 'cordifolia')->first(); if ($cordifolia == null) {$cordifolia = \App\Models\Species::create(['genus' => 'Aptenia', 'taxon' => 'cordifolia', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $cordifolia->esname = 'Rocío africano'; $cordifolia->save();}
        $edulis = \App\Models\Species::where('genus', 'Carpobrotus')->where('taxon', 'edulis')->first(); if ($edulis == null) {$edulis = \App\Models\Species::create(['genus' => 'Carpobrotus', 'taxon' => 'edulis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $edulis->esname = 'Uña de gato'; $edulis->save();}
        $chamaecyparissus = \App\Models\Species::where('genus', 'Santolina')->where('taxon', 'chamaecyparissus')->first(); if ($chamaecyparissus == null) {$chamaecyparissus = \App\Models\Species::create(['genus' => 'Santolina', 'taxon' => 'chamaecyparissus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $chamaecyparissus->esname = 'Abrótano hembra'; $chamaecyparissus->save();}
        $rosmarinifolia = \App\Models\Species::where('genus', 'Santolina')->where('taxon', 'rosmarinifolia')->first(); if ($rosmarinifolia == null) {$rosmarinifolia = \App\Models\Species::create(['genus' => 'Santolina', 'taxon' => 'rosmarinifolia', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $rosmarinifolia->esname = 'Botonera'; $rosmarinifolia->save();}
        $stoechas = \App\Models\Species::where('genus', 'Helichrysum')->where('taxon', 'stoechas')->first(); if ($stoechas == null) {$stoechas = \App\Models\Species::create(['genus' => 'Helichrysum', 'taxon' => 'stoechas', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $stoechas->esname = 'Helichrysum'; $stoechas->save();}
        $maritima = \App\Models\Species::where('genus', 'Lobularia')->where('taxon', 'maritima')->first(); if ($maritima == null) {$maritima = \App\Models\Species::create(['genus' => 'Lobularia', 'taxon' => 'maritima', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $maritima->esname = 'Aliso marítimo'; $maritima->save();}
        $sempervirens = \App\Models\Species::where('genus', 'Iberis')->where('taxon', 'sempervirens')->first(); if ($sempervirens == null) {$sempervirens = \App\Models\Species::create(['genus' => 'Iberis', 'taxon' => 'sempervirens', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sempervirens->esname = 'Canasta de plata'; $sempervirens->save();}
        $vulgaris = \App\Models\Species::where('genus', 'Thymus')->where('taxon', 'vulgaris')->first(); if ($vulgaris == null) {$vulgaris = \App\Models\Species::create(['genus' => 'Thymus', 'taxon' => 'vulgaris', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $vulgaris->esname = 'Tomillo'; $vulgaris->save();}
        $serpyllum = \App\Models\Species::where('genus', 'Thymus')->where('taxon', 'serpyllum')->first(); if ($serpyllum == null) {$serpyllum = \App\Models\Species::create(['genus' => 'Thymus', 'taxon' => 'serpyllum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $serpyllum->esname = 'Serpol'; $serpyllum->save();}
        $viravira = \App\Models\Species::where('genus', 'Senecio')->where('taxon', 'viravira')->first(); if ($viravira == null) {$viravira = \App\Models\Species::create(['genus' => 'Senecio', 'taxon' => 'viravira', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $viravira->esname = 'Senecio'; $viravira->save();}
        $dealbata = \App\Models\Species::where('genus', 'Acacia')->where('taxon', 'dealbata')->first(); if ($dealbata == null) {$dealbata = \App\Models\Species::create(['genus' => 'Acacia', 'taxon' => 'dealbata', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $dealbata->esname = 'Mimosa'; $dealbata->save();}
        $salicina = \App\Models\Species::where('genus', 'Acacia')->where('taxon', 'salicina')->first(); if ($salicina == null) {$salicina = \App\Models\Species::create(['genus' => 'Acacia', 'taxon' => 'salicina', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $salicina->esname = 'Acacia de hoja de sauce'; $salicina->save();}
        $unedo = \App\Models\Species::where('genus', 'Arbutus')->where('taxon', 'unedo')->first(); if ($unedo == null) {$unedo = \App\Models\Species::create(['genus' => 'Arbutus', 'taxon' => 'unedo', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $unedo->esname = 'Madroño'; $unedo->save();}
        $viminalis = \App\Models\Species::where('genus', 'Callistemon')->where('taxon', 'viminalis')->first(); if ($viminalis == null) {$viminalis = \App\Models\Species::create(['genus' => 'Callistemon', 'taxon' => 'viminalis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $viminalis->esname = 'Calistemon llorón'; $viminalis->save();}
        $siliqua = \App\Models\Species::where('genus', 'Ceratonia')->where('taxon', 'siliqua')->first(); if ($siliqua == null) {$siliqua = \App\Models\Species::create(['genus' => 'Ceratonia', 'taxon' => 'siliqua', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $siliqua->esname = 'Algarrobo'; $siliqua->save();}
        $siliquastrum = \App\Models\Species::where('genus', 'Cercis')->where('taxon', 'siliquastrum')->first(); if ($siliquastrum == null) {$siliquastrum = \App\Models\Species::create(['genus' => 'Cercis', 'taxon' => 'siliquastrum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $siliquastrum->esname = 'Árbol del amor'; $siliquastrum->save();}
        $officinalis = \App\Models\Species::where('genus', 'Lavandula')->where('taxon', 'officinalis')->first(); if ($officinalis == null) {$officinalis = \App\Models\Species::create(['genus' => 'Lavandula', 'taxon' => 'officinalis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $officinalis->esname = 'Lavanda'; $officinalis->save();}
        $sativa = \App\Models\Species::where('genus', 'Mentha')->where('taxon', 'sativa')->first(); if ($sativa == null) {$sativa = \App\Models\Species::create(['genus' => 'Mentha', 'taxon' => 'sativa', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sativa->esname = 'Hierbabuena'; $sativa->save();}
        $piperita = \App\Models\Species::where('genus', 'Mentha')->where('taxon', 'piperita')->first(); if ($piperita == null) {$piperita = \App\Models\Species::create(['genus' => 'Mentha', 'taxon' => 'piperita', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $piperita->esname = 'Menta negra'; $piperita->save();}
        $pulegium = \App\Models\Species::where('genus', 'Mentha')->where('taxon', 'pulegium')->first(); if ($pulegium == null) {$pulegium = \App\Models\Species::create(['genus' => 'Mentha', 'taxon' => 'pulegium', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $pulegium->esname = 'Menta poleo'; $pulegium->save();}
        $vulgare = \App\Models\Species::where('genus', 'Foeniculum')->where('taxon', 'vulgare')->first(); if ($vulgare == null) {$vulgare = \App\Models\Species::create(['genus' => 'Foeniculum', 'taxon' => 'vulgare', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $vulgare->esname = 'Hinojo'; $vulgare->save();}
        $albidus = \App\Models\Species::where('genus', 'Cistus')->where('taxon', 'albidus')->first(); if ($albidus == null) {$albidus = \App\Models\Species::create(['genus' => 'Cistus', 'taxon' => 'albidus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $albidus->esname = 'Estepa blanca'; $albidus->save();}
        $crispus = \App\Models\Species::where('genus', 'Cistus')->where('taxon', 'crispus')->first(); if ($crispus == null) {$crispus = \App\Models\Species::create(['genus' => 'Cistus', 'taxon' => 'crispus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $crispus->esname = 'Jara rizada'; $crispus->save();}
        $salviifolius = \App\Models\Species::where('genus', 'Cistus')->where('taxon', 'salviifolius')->first(); if ($salviifolius == null) {$salviifolius = \App\Models\Species::create(['genus' => 'Cistus', 'taxon' => 'salviifolius', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $salviifolius->esname = 'Jara negra'; $salviifolius->save();}
        $monspeliensis = \App\Models\Species::where('genus', 'Cistus')->where('taxon', 'monspeliensis')->first(); if ($monspeliensis == null) {$monspeliensis = \App\Models\Species::create(['genus' => 'Cistus', 'taxon' => 'monspeliensis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $monspeliensis->esname = 'Estepa morisca'; $monspeliensis->save();}
        $ladanifer = \App\Models\Species::where('genus', 'Cistus')->where('taxon', 'ladanifer')->first(); if ($ladanifer == null) {$ladanifer = \App\Models\Species::create(['genus' => 'Cistus', 'taxon' => 'ladanifer', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $ladanifer->esname = 'Jara pringosa'; $ladanifer->save();}
        $ulmifolius = \App\Models\Species::where('genus', 'Rubus')->where('taxon', 'ulmifolius')->first(); if ($ulmifolius == null) {$ulmifolius = \App\Models\Species::create(['genus' => 'Rubus', 'taxon' => 'ulmifolius', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $ulmifolius->esname = 'Zarzamora'; $ulmifolius->save();}
        $idaeus = \App\Models\Species::where('genus', 'Rubus')->where('taxon', 'idaeus')->first(); if ($idaeus == null) {$idaeus = \App\Models\Species::create(['genus' => 'Rubus', 'taxon' => 'idaeus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $idaeus->esname = 'Frambueso'; $idaeus->save();}
        $canina = \App\Models\Species::where('genus', 'Rosa')->where('taxon', 'canina')->first(); if ($canina == null) {$canina = \App\Models\Species::create(['genus' => 'Rosa', 'taxon' => 'canina', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $canina->esname = 'Rosa silvestre'; $canina->save();}
        $monogyna = \App\Models\Species::where('genus', 'Crataegus')->where('taxon', 'monogyna')->first(); if ($monogyna == null) {$monogyna = \App\Models\Species::create(['genus' => 'Crataegus', 'taxon' => 'monogyna', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $monogyna->esname = 'Espino blanco'; $monogyna->save();}
        $aspera = \App\Models\Species::where('genus', 'Smilax')->where('taxon', 'aspera')->first(); if ($aspera == null) {$aspera = \App\Models\Species::create(['genus' => 'Smilax', 'taxon' => 'aspera', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $aspera->esname = 'Zarzaparrilla'; $aspera->save();}
        $helix = \App\Models\Species::where('genus', 'Hedera')->where('taxon', 'helix')->first(); if ($helix == null) {$helix = \App\Models\Species::create(['genus' => 'Hedera', 'taxon' => 'helix', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $helix->esname = 'Hiedra'; $helix->save();}
        $officinale = \App\Models\Species::where('genus', 'Jasminum')->where('taxon', 'officinale')->first(); if ($officinale == null) {$officinale = \App\Models\Species::create(['genus' => 'Jasminum', 'taxon' => 'officinale', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $officinale->esname = 'Jazmín'; $officinale->save();}
        $altissima = \App\Models\Species::where('genus', 'Ailanthus')->where('taxon', 'altissima')->first(); if ($altissima == null) {$altissima = \App\Models\Species::create(['genus' => 'Ailanthus', 'taxon' => 'altissima', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $altissima->esname = 'Ailanto'; $altissima->save();}
        $sempervirens = \App\Models\Species::where('genus', 'Buxus')->where('taxon', 'sempervirens')->first(); if ($sempervirens == null) {$sempervirens = \App\Models\Species::create(['genus' => 'Buxus', 'taxon' => 'sempervirens', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sempervirens->esname = 'Boj'; $sempervirens->save();}
        $parviflora = \App\Models\Species::where('genus', 'Tamarix')->where('taxon', 'parviflora')->first(); if ($parviflora == null) {$parviflora = \App\Models\Species::create(['genus' => 'Tamarix', 'taxon' => 'parviflora', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $parviflora->esname = 'Taray'; $parviflora->save();}
        $gallica = \App\Models\Species::where('genus', 'Tamarix')->where('taxon', 'gallica')->first(); if ($gallica == null) {$gallica = \App\Models\Species::create(['genus' => 'Tamarix', 'taxon' => 'gallica', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $gallica->esname = 'Tamariz'; $gallica->save();}
        $camaldulensis = \App\Models\Species::where('genus', 'Eucalyptus')->where('taxon', 'camaldulensis')->first(); if ($camaldulensis == null) {$camaldulensis = \App\Models\Species::create(['genus' => 'Eucalyptus', 'taxon' => 'camaldulensis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $camaldulensis->esname = 'Eucalipto '; $camaldulensis->save();}
        $communis = \App\Models\Species::where('genus', 'Myrtus')->where('taxon', 'communis')->first(); if ($communis == null) {$communis = \App\Models\Species::create(['genus' => 'Myrtus', 'taxon' => 'communis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $communis->esname = 'Mirto'; $communis->save();}
        $carica = \App\Models\Species::where('genus', 'Ficus')->where('taxon', 'carica')->first(); if ($carica == null) {$carica = \App\Models\Species::create(['genus' => 'Ficus', 'taxon' => 'carica', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $carica->esname = 'Higuera '; $carica->save();}
        $sylvestris = \App\Models\Species::where('genus', 'Malus')->where('taxon', 'sylvestris')->first(); if ($sylvestris == null) {$sylvestris = \App\Models\Species::create(['genus' => 'Malus', 'taxon' => 'sylvestris', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sylvestris->esname = 'Manzano '; $sylvestris->save();}
        $dulcis = \App\Models\Species::where('genus', 'Prunus')->where('taxon', 'dulcis')->first(); if ($dulcis == null) {$dulcis = \App\Models\Species::create(['genus' => 'Prunus', 'taxon' => 'dulcis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $dulcis->esname = 'Almendro'; $dulcis->save();}
        $domestica = \App\Models\Species::where('genus', 'Prunus')->where('taxon', 'domestica')->first(); if ($domestica == null) {$domestica = \App\Models\Species::create(['genus' => 'Prunus', 'taxon' => 'domestica', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $domestica->esname = 'Ciruelo '; $domestica->save();}
        $avium = \App\Models\Species::where('genus', 'Prunus')->where('taxon', 'avium')->first(); if ($avium == null) {$avium = \App\Models\Species::create(['genus' => 'Prunus', 'taxon' => 'avium', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $avium->esname = 'Cerezo '; $avium->save();}
        $communis = \App\Models\Species::where('genus', 'Pyrus')->where('taxon', 'communis')->first(); if ($communis == null) {$communis = \App\Models\Species::create(['genus' => 'Pyrus', 'taxon' => 'communis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $communis->esname = 'Peral'; $communis->save();}
        $nigra = \App\Models\Species::where('genus', 'Sambucus')->where('taxon', 'nigra')->first(); if ($nigra == null) {$nigra = \App\Models\Species::create(['genus' => 'Sambucus', 'taxon' => 'nigra', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $nigra->esname = 'Sauco negro'; $nigra->save();}
        $alba = \App\Models\Species::where('genus', 'Salix')->where('taxon', 'alba')->first(); if ($alba == null) {$alba = \App\Models\Species::create(['genus' => 'Salix', 'taxon' => 'alba', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $alba->esname = 'Sauce'; $alba->save();}
        $litigiosum = \App\Models\Species::where('genus', 'Antirrhinum')->where('taxon', 'litigiosum')->first(); if ($litigiosum == null) {$litigiosum = \App\Models\Species::create(['genus' => 'Antirrhinum', 'taxon' => 'litigiosum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $litigiosum->esname = 'Boca de dragón'; $litigiosum->save();}
        $lindheimeri = \App\Models\Species::where('genus', 'Gaura')->where('taxon', 'lindheimeri')->first(); if ($lindheimeri == null) {$lindheimeri = \App\Models\Species::create(['genus' => 'Gaura', 'taxon' => 'lindheimeri', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $lindheimeri->esname = 'Gaura'; $lindheimeri->save();}
        $oleander = \App\Models\Species::where('genus', 'Nerium')->where('taxon', 'oleander')->first(); if ($oleander == null) {$oleander = \App\Models\Species::create(['genus' => 'Nerium', 'taxon' => 'oleander', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $oleander->esname = 'Adelfa'; $oleander->save();}
        $officinalis = \App\Models\Species::where('genus', 'Salvia')->where('taxon', 'officinalis')->first(); if ($officinalis == null) {$officinalis = \App\Models\Species::create(['genus' => 'Salvia', 'taxon' => 'officinalis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $officinalis->esname = 'Salvia'; $officinalis->save();}
        $rosmarinus = \App\Models\Species::where('genus', 'Salvia')->where('taxon', 'rosmarinus')->first(); if ($rosmarinus == null) {$rosmarinus = \App\Models\Species::create(['genus' => 'Salvia', 'taxon' => 'rosmarinus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $rosmarinus->esname = 'Romero'; $rosmarinus->save();}
        $officinalis = \App\Models\Species::where('genus', 'Rosmarinus')->where('taxon', 'officinalis prostratus')->first(); if ($officinalis == null) {$officinalis = \App\Models\Species::create(['genus' => 'Rosmarinus', 'taxon' => 'officinalis prostratus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $officinalis->esname = 'Romero rastrero'; $officinalis->save();}
        $vulgaris = \App\Models\Species::where('genus', 'Calluna')->where('taxon', 'vulgaris')->first(); if ($vulgaris == null) {$vulgaris = \App\Models\Species::create(['genus' => 'Calluna', 'taxon' => 'vulgaris', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $vulgaris->esname = 'Brecina'; $vulgaris->save();}
        $multiflora = \App\Models\Species::where('genus', 'Erica')->where('taxon', 'multiflora')->first(); if ($multiflora == null) {$multiflora = \App\Models\Species::create(['genus' => 'Erica', 'taxon' => 'multiflora', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $multiflora->esname = 'Brezo'; $multiflora->save();}
        $arborea = \App\Models\Species::where('genus', 'Erica')->where('taxon', 'arborea')->first(); if ($arborea == null) {$arborea = \App\Models\Species::create(['genus' => 'Erica', 'taxon' => 'arborea', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $arborea->esname = 'Brezo blanco'; $arborea->save();}
        $florida = \App\Models\Species::where('genus', 'Genista')->where('taxon', 'florida')->first(); if ($florida == null) {$florida = \App\Models\Species::create(['genus' => 'Genista', 'taxon' => 'florida', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $florida->esname = 'Piorno'; $florida->save();}
        $lasianthum = \App\Models\Species::where('genus', 'Halimium')->where('taxon', 'lasianthum')->first(); if ($lasianthum == null) {$lasianthum = \App\Models\Species::create(['genus' => 'Halimium', 'taxon' => 'lasianthum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $lasianthum->esname = 'Jara lanuda'; $lasianthum->save();}
        $assoi = \App\Models\Species::where('genus', 'Carduus')->where('taxon', 'assoi')->first(); if ($assoi == null) {$assoi = \App\Models\Species::create(['genus' => 'Carduus', 'taxon' => 'assoi', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $assoi->esname = 'Cardo borriquero'; $assoi->save();}
        $langei = \App\Models\Species::where('genus', 'Orchis')->where('taxon', 'langei')->first(); if ($langei == null) {$langei = \App\Models\Species::create(['genus' => 'Orchis', 'taxon' => 'langei', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $langei->esname = 'Orquídea de Lange'; $langei->save();}
        $parviflorus = \App\Models\Species::where('genus', 'Ulex')->where('taxon', 'parviflorus')->first(); if ($parviflorus == null) {$parviflorus = \App\Models\Species::create(['genus' => 'Ulex', 'taxon' => 'parviflorus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $parviflorus->esname = 'Aliaga'; $parviflorus->save();}
        $monspeliensis = \App\Models\Species::where('genus', 'Aphyllanthes')->where('taxon', 'monspeliensis')->first(); if ($monspeliensis == null) {$monspeliensis = \App\Models\Species::create(['genus' => 'Aphyllanthes', 'taxon' => 'monspeliensis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $monspeliensis->esname = 'Falso junquillo'; $monspeliensis->save();}
        $zanonii = \App\Models\Species::where('genus', 'Argyrolobium')->where('taxon', 'zanonii')->first(); if ($zanonii == null) {$zanonii = \App\Models\Species::create(['genus' => 'Argyrolobium', 'taxon' => 'zanonii', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $zanonii->esname = 'Hierba de plata'; $zanonii->save();}
        $gomezcampoi = \App\Models\Species::where('genus', 'Erysimum')->where('taxon', 'gomezcampoi')->first(); if ($gomezcampoi == null) {$gomezcampoi = \App\Models\Species::create(['genus' => 'Erysimum', 'taxon' => 'gomezcampoi', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $gomezcampoi->esname = 'Hierba de San Jaime'; $gomezcampoi->save();}
        $cinerea = \App\Models\Species::where('genus', 'Genista')->where('taxon', 'cinerea')->first(); if ($cinerea == null) {$cinerea = \App\Models\Species::create(['genus' => 'Genista', 'taxon' => 'cinerea', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $cinerea->esname = 'Genista'; $cinerea->save();}
        $implexa = \App\Models\Species::where('genus', 'Lonicera')->where('taxon', 'implexa')->first(); if ($implexa == null) {$implexa = \App\Models\Species::create(['genus' => 'Lonicera', 'taxon' => 'implexa', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $implexa->esname = 'Madreselva silvestre'; $implexa->save();}
        $fruticosa = \App\Models\Species::where('genus', 'Satureja')->where('taxon', 'fruticosa')->first(); if ($fruticosa == null) {$fruticosa = \App\Models\Species::create(['genus' => 'Satureja', 'taxon' => 'fruticosa', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $fruticosa->esname = 'Ajedrea blanca'; $fruticosa->save();}
        $purpurea = \App\Models\Species::where('genus', 'Phlomis')->where('taxon', 'purpurea')->first(); if ($purpurea == null) {$purpurea = \App\Models\Species::create(['genus' => 'Phlomis', 'taxon' => 'purpurea', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $purpurea->esname = 'Phlomis'; $purpurea->save();}
        $odoratissimum = \App\Models\Species::where('genus', 'Viburnum')->where('taxon', 'odoratissimum')->first(); if ($odoratissimum == null) {$odoratissimum = \App\Models\Species::create(['genus' => 'Viburnum', 'taxon' => 'odoratissimum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $odoratissimum->esname = 'Viburno dulce'; $odoratissimum->save();}
        $spinosa = \App\Models\Species::where('genus', 'Vella')->where('taxon', 'spinosa')->first(); if ($spinosa == null) {$spinosa = \App\Models\Species::create(['genus' => 'Vella', 'taxon' => 'spinosa', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $spinosa->esname = 'Piorno de crucetillas'; $spinosa->save();}
        $humilis = \App\Models\Species::where('genus', 'Atractylis')->where('taxon', 'humilis')->first(); if ($humilis == null) {$humilis = \App\Models\Species::create(['genus' => 'Atractylis', 'taxon' => 'humilis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $humilis->esname = 'Cardo heredero'; $humilis->save();}
        $halimifolium = \App\Models\Species::where('genus', 'Halimium')->where('taxon', 'halimifolium')->first(); if ($halimifolium == null) {$halimifolium = \App\Models\Species::create(['genus' => 'Halimium', 'taxon' => 'halimifolium', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $halimifolium->esname = 'Jaguarzo blanco'; $halimifolium->save();}
        $spectabilis = \App\Models\Species::where('genus', 'Bouganvillea')->where('taxon', 'spectabilis')->first(); if ($spectabilis == null) {$spectabilis = \App\Models\Species::create(['genus' => 'Bouganvillea', 'taxon' => 'spectabilis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $spectabilis->esname = 'Buganvilla'; $spectabilis->save();}
        $maritima = \App\Models\Species::where('genus', 'Pallenis')->where('taxon', 'maritima')->first(); if ($maritima == null) {$maritima = \App\Models\Species::create(['genus' => 'Pallenis', 'taxon' => 'maritima', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $maritima->esname = 'Pallenis'; $maritima->save();}
        $nobilis = \App\Models\Species::where('genus', 'Laurus')->where('taxon', 'nobilis')->first(); if ($nobilis == null) {$nobilis = \App\Models\Species::create(['genus' => 'Laurus', 'taxon' => 'nobilis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $nobilis->esname = 'Laurel'; $nobilis->save();}
        $cytisoides = \App\Models\Species::where('genus', 'Anthyllis')->where('taxon', 'cytisoides')->first(); if ($cytisoides == null) {$cytisoides = \App\Models\Species::create(['genus' => 'Anthyllis', 'taxon' => 'cytisoides', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $cytisoides->esname = 'Anthyllis'; $cytisoides->save();}
        $cneorum = \App\Models\Species::where('genus', 'Convolvulus')->where('taxon', 'cneorum')->first(); if ($cneorum == null) {$cneorum = \App\Models\Species::create(['genus' => 'Convolvulus', 'taxon' => 'cneorum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $cneorum->esname = 'Convolvulus'; $cneorum->save();}
        $juncea = \App\Models\Species::where('genus', 'Coronilla')->where('taxon', 'juncea')->first(); if ($juncea == null) {$juncea = \App\Models\Species::create(['genus' => 'Coronilla', 'taxon' => 'juncea', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $juncea->esname = 'Coronilla '; $juncea->save();}
        $punctatum = \App\Models\Species::where('genus', 'Hypericum')->where('taxon', 'punctatum')->first(); if ($punctatum == null) {$punctatum = \App\Models\Species::create(['genus' => 'Hypericum', 'taxon' => 'punctatum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $punctatum->esname = 'Hierba de San Juan'; $punctatum->save();}
        $sylvestris = \App\Models\Species::where('genus', 'Malva')->where('taxon', 'sylvestris')->first(); if ($sylvestris == null) {$sylvestris = \App\Models\Species::create(['genus' => 'Malva', 'taxon' => 'sylvestris', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sylvestris->esname = 'Malva '; $sylvestris->save();}
        $sphaerocarpa = \App\Models\Species::where('genus', 'Retama')->where('taxon', 'sphaerocarpa')->first(); if ($sphaerocarpa == null) {$sphaerocarpa = \App\Models\Species::create(['genus' => 'Retama', 'taxon' => 'sphaerocarpa', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sphaerocarpa->esname = 'Retama'; $sphaerocarpa->save();}
        $auriculata = \App\Models\Species::where('genus', 'Plumbago')->where('taxon', 'auriculata')->first(); if ($auriculata == null) {$auriculata = \App\Models\Species::create(['genus' => 'Plumbago', 'taxon' => 'auriculata', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $auriculata->esname = 'Jazmín azul'; $auriculata->save();}
        $sativum = \App\Models\Species::where('genus', 'Allium')->where('taxon', 'sativum')->first(); if ($sativum == null) {$sativum = \App\Models\Species::create(['genus' => 'Allium', 'taxon' => 'sativum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sativum->esname = 'Ajo'; $sativum->save();}
        $cepa = \App\Models\Species::where('genus', 'Allium')->where('taxon', 'cepa')->first(); if ($cepa == null) {$cepa = \App\Models\Species::create(['genus' => 'Allium', 'taxon' => 'cepa', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $cepa->esname = 'Cebolla'; $cepa->save();}
        $porrum = \App\Models\Species::where('genus', 'Allium')->where('taxon', 'porrum')->first(); if ($porrum == null) {$porrum = \App\Models\Species::create(['genus' => 'Allium', 'taxon' => 'porrum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $porrum->esname = 'Puerro'; $porrum->save();}
        $oleracea = \App\Models\Species::where('genus', 'Brassica ')->where('taxon', 'oleracea')->first(); if ($oleracea == null) {$oleracea = \App\Models\Species::create(['genus' => 'Brassica ', 'taxon' => 'oleracea', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $oleracea->esname = 'Col'; $oleracea->save();}
        $lycopersicum = \App\Models\Species::where('genus', 'Solanum')->where('taxon', 'lycopersicum')->first(); if ($lycopersicum == null) {$lycopersicum = \App\Models\Species::create(['genus' => 'Solanum', 'taxon' => 'lycopersicum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $lycopersicum->esname = 'Tomate'; $lycopersicum->save();}
        $annuum = \App\Models\Species::where('genus', 'Capsicum')->where('taxon', 'annuum')->first(); if ($annuum == null) {$annuum = \App\Models\Species::create(['genus' => 'Capsicum', 'taxon' => 'annuum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $annuum->esname = 'Pimiento'; $annuum->save();}
        $melongena = \App\Models\Species::where('genus', 'Solanum ')->where('taxon', 'melongena')->first(); if ($melongena == null) {$melongena = \App\Models\Species::create(['genus' => 'Solanum ', 'taxon' => 'melongena', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $melongena->esname = 'Berenjena'; $melongena->save();}
        $pepo = \App\Models\Species::where('genus', 'Cucurbita ')->where('taxon', 'pepo')->first(); if ($pepo == null) {$pepo = \App\Models\Species::create(['genus' => 'Cucurbita ', 'taxon' => 'pepo', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $pepo->esname = 'Calabacín'; $pepo->save();}
        $maxima = \App\Models\Species::where('genus', 'Cucurbita ')->where('taxon', 'maxima')->first(); if ($maxima == null) {$maxima = \App\Models\Species::create(['genus' => 'Cucurbita ', 'taxon' => 'maxima', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $maxima->esname = 'Calabaza'; $maxima->save();}
        $melo = \App\Models\Species::where('genus', 'Cucumis')->where('taxon', 'melo')->first(); if ($melo == null) {$melo = \App\Models\Species::create(['genus' => 'Cucumis', 'taxon' => 'melo', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $melo->esname = 'Melón'; $melo->save();}
        $lanatus = \App\Models\Species::where('genus', 'Citrullus')->where('taxon', 'lanatus')->first(); if ($lanatus == null) {$lanatus = \App\Models\Species::create(['genus' => 'Citrullus', 'taxon' => 'lanatus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $lanatus->esname = 'Sandía'; $lanatus->save();}
        $sativus = \App\Models\Species::where('genus', 'Cucumis')->where('taxon', 'sativus')->first(); if ($sativus == null) {$sativus = \App\Models\Species::create(['genus' => 'Cucumis', 'taxon' => 'sativus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sativus->esname = 'Pepino'; $sativus->save();}
        $cardunculus = \App\Models\Species::where('genus', 'Cynara')->where('taxon', 'cardunculus')->first(); if ($cardunculus == null) {$cardunculus = \App\Models\Species::create(['genus' => 'Cynara', 'taxon' => 'cardunculus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $cardunculus->esname = 'Alcachofa'; $cardunculus->save();}
        $faba = \App\Models\Species::where('genus', 'Vicia')->where('taxon', 'faba')->first(); if ($faba == null) {$faba = \App\Models\Species::create(['genus' => 'Vicia', 'taxon' => 'faba', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $faba->esname = 'Haba'; $faba->save();}
        $vulgaris = \App\Models\Species::where('genus', 'Phaseolus ')->where('taxon', 'vulgaris')->first(); if ($vulgaris == null) {$vulgaris = \App\Models\Species::create(['genus' => 'Phaseolus ', 'taxon' => 'vulgaris', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $vulgaris->esname = 'Judía verde'; $vulgaris->save();}
        $sativum = \App\Models\Species::where('genus', 'Pisum')->where('taxon', 'sativum')->first(); if ($sativum == null) {$sativum = \App\Models\Species::create(['genus' => 'Pisum', 'taxon' => 'sativum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sativum->esname = 'Guisante'; $sativum->save();}
        $crispum = \App\Models\Species::where('genus', 'Petroselinum')->where('taxon', 'crispum')->first(); if ($crispum == null) {$crispum = \App\Models\Species::create(['genus' => 'Petroselinum', 'taxon' => 'crispum', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $crispum->esname = 'Perejil'; $crispum->save();}
        $carota = \App\Models\Species::where('genus', 'Daucus')->where('taxon', 'carota')->first(); if ($carota == null) {$carota = \App\Models\Species::create(['genus' => 'Daucus', 'taxon' => 'carota', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $carota->esname = 'Zanahoria'; $carota->save();}
        $vesca = \App\Models\Species::where('genus', 'Fragaria')->where('taxon', 'vesca')->first(); if ($vesca == null) {$vesca = \App\Models\Species::create(['genus' => 'Fragaria', 'taxon' => 'vesca', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $vesca->esname = 'Fresa'; $vesca->save();}
        $rapa = \App\Models\Species::where('genus', 'Brassica ')->where('taxon', 'rapa')->first(); if ($rapa == null) {$rapa = \App\Models\Species::create(['genus' => 'Brassica ', 'taxon' => 'rapa', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $rapa->esname = 'Nabo'; $rapa->save();}
        $sativus = \App\Models\Species::where('genus', 'Raphanus')->where('taxon', 'sativus')->first(); if ($sativus == null) {$sativus = \App\Models\Species::create(['genus' => 'Raphanus', 'taxon' => 'sativus', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $sativus->esname = 'Rábano'; $sativus->save();}
        $graveolens = \App\Models\Species::where('genus', 'Apium ')->where('taxon', 'graveolens')->first(); if ($graveolens == null) {$graveolens = \App\Models\Species::create(['genus' => 'Apium ', 'taxon' => 'graveolens', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $graveolens->esname = 'Apio'; $graveolens->save();}
        $officinalis = \App\Models\Species::where('genus', 'Asparagus')->where('taxon', 'officinalis')->first(); if ($officinalis == null) {$officinalis = \App\Models\Species::create(['genus' => 'Asparagus', 'taxon' => 'officinalis', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $officinalis->esname = 'Espárrago'; $officinalis->save();}
        $calendula = \App\Models\Species::where('genus', 'Arctotheca')->where('taxon', 'calendula')->first(); if ($calendula == null) {$calendula = \App\Models\Species::create(['genus' => 'Arctotheca', 'taxon' => 'calendula', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $calendula->esname = 'Margarita amarilla'; $calendula->save();}
        $pescaprae = \App\Models\Species::where('genus', 'Oxalis')->where('taxon', 'pes-caprae')->first(); if ($pescaprae == null) {$pescaprae = \App\Models\Species::create(['genus' => 'Oxalis', 'taxon' => 'pes-caprae', 'speciesgroup_id' => $plantSGid, 'taxrank' => 'species']); $pescaprae->esname = 'Vinagritos'; $pescaprae->save();}

        $this->info("Done!");
    }
}
